#!/usr/bin/env bash
# OUTDIR=$(xdg-user-dir PICTURES)
OUTDIR="$HOME/media/images/screenshots"

if [ ! -d $OUTDIR ]; then
    mkdir -p $OUTDIR
fi

LABEL="$OUTDIR/$(date +'screenshot_%Y-%M-%d.%H%m%S.png')"

# get screen slection
COORD="$(slurp)"
# detect if escaped early and exit
if [ -z "$COORD" ]; then
    exit 0;
fi

# grab the screenshot and notify dunst
grim -g "${COORD}" $LABEL
ACTION=$(dunstify -i $LABEL --action="clip,Clipboard" "Screenshot saved" "$LABEL")

# copy the image to the clipboard by default
cat $LABEL | wl-copy

