#!/usr/bin/env bash
# Collect a list of Sway node names and feed them to fuzzel to allow user to pick a window to focus.

# Grab the list of nodes using swaymsg and jq to filter the json response
NODES=$(swaymsg -t get_tree | jq -r \
'.. | (.nodes? // empty)[] | select(.pid) | {id} + {name}')

# Grab node names list
NODE_NAMES=$(echo "$NODES" | jq .name)

# pass the list of node names to fuzzel for selection
SELECTED=$(echo "$NODE_NAMES" | fuzzel -d -w 64 -I)

# Focus the selected window by using swaymsg
if [ ! -z "$SELECTED" ]; then
    NODE_ID=$(echo "$NODES" | jq '. | select(.name == '"$SELECTED"') | .id')
    swaymsg "[con_id=$NODE_ID] focus"
fi
